/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardWalletRouteImport } from './routes/dashboard.wallet'
import { Route as DashboardTransactionsRouteImport } from './routes/dashboard.transactions'
import { Route as DashboardLogsRouteImport } from './routes/dashboard.logs'
import { Route as DashboardKeysRouteImport } from './routes/dashboard.keys'
import { Route as DashboardDocsRouteImport } from './routes/dashboard.docs'
import { Route as DashboardCallbacksRouteImport } from './routes/dashboard.callbacks'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminStatsRouteImport } from './routes/admin.stats'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminIntegrationRouteImport } from './routes/admin.integration'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminDocsRouteImport } from './routes/admin.docs'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminCallbacksRouteImport } from './routes/admin.callbacks'
import { Route as AdminCacheRouteImport } from './routes/admin.cache'
import { Route as ApiPublicWalletRouteImport } from './routes/api/public/wallet'
import { Route as ApiPublicSametrendRouteImport } from './routes/api/public/sametrend'
import { Route as ApiPublicProxyRouteImport } from './routes/api/public/proxy'
import { Route as ApiPublicBondpayCallbackRouteImport } from './routes/api/public/bondpay-callback'
import { Route as ApiPublicTokenValidateRouteImport } from './routes/api/public/token/validate'
import { Route as ApiPublicTokenIssueRouteImport } from './routes/api/public/token/issue'
import { Route as ApiPublicTokenEnterRouteImport } from './routes/api/public/token/enter'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardWalletRoute = DashboardWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKeysRoute = DashboardKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocsRoute = DashboardDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCallbacksRoute = DashboardCallbacksRouteImport.update({
  id: '/callbacks',
  path: '/callbacks',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationRoute = AdminIntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocsRoute = AdminDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCallbacksRoute = AdminCallbacksRouteImport.update({
  id: '/callbacks',
  path: '/callbacks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCacheRoute = AdminCacheRouteImport.update({
  id: '/cache',
  path: '/cache',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicWalletRoute = ApiPublicWalletRouteImport.update({
  id: '/api/public/wallet',
  path: '/api/public/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSametrendRoute = ApiPublicSametrendRouteImport.update({
  id: '/api/public/sametrend',
  path: '/api/public/sametrend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProxyRoute = ApiPublicProxyRouteImport.update({
  id: '/api/public/proxy',
  path: '/api/public/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBondpayCallbackRoute =
  ApiPublicBondpayCallbackRouteImport.update({
    id: '/api/public/bondpay-callback',
    path: '/api/public/bondpay-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTokenValidateRoute = ApiPublicTokenValidateRouteImport.update({
  id: '/api/public/token/validate',
  path: '/api/public/token/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTokenIssueRoute = ApiPublicTokenIssueRouteImport.update({
  id: '/api/public/token/issue',
  path: '/api/public/token/issue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTokenEnterRoute = ApiPublicTokenEnterRouteImport.update({
  id: '/api/public/token/enter',
  path: '/api/public/token/enter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/cache': typeof AdminCacheRoute
  '/admin/callbacks': typeof AdminCallbacksRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/docs': typeof AdminDocsRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/integration': typeof AdminIntegrationRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/callbacks': typeof DashboardCallbacksRoute
  '/dashboard/docs': typeof DashboardDocsRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/bondpay-callback': typeof ApiPublicBondpayCallbackRoute
  '/api/public/proxy': typeof ApiPublicProxyRoute
  '/api/public/sametrend': typeof ApiPublicSametrendRoute
  '/api/public/wallet': typeof ApiPublicWalletRoute
  '/api/public/token/enter': typeof ApiPublicTokenEnterRoute
  '/api/public/token/issue': typeof ApiPublicTokenIssueRoute
  '/api/public/token/validate': typeof ApiPublicTokenValidateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/cache': typeof AdminCacheRoute
  '/admin/callbacks': typeof AdminCallbacksRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/docs': typeof AdminDocsRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/integration': typeof AdminIntegrationRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/callbacks': typeof DashboardCallbacksRoute
  '/dashboard/docs': typeof DashboardDocsRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/bondpay-callback': typeof ApiPublicBondpayCallbackRoute
  '/api/public/proxy': typeof ApiPublicProxyRoute
  '/api/public/sametrend': typeof ApiPublicSametrendRoute
  '/api/public/wallet': typeof ApiPublicWalletRoute
  '/api/public/token/enter': typeof ApiPublicTokenEnterRoute
  '/api/public/token/issue': typeof ApiPublicTokenIssueRoute
  '/api/public/token/validate': typeof ApiPublicTokenValidateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/cache': typeof AdminCacheRoute
  '/admin/callbacks': typeof AdminCallbacksRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/docs': typeof AdminDocsRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/integration': typeof AdminIntegrationRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/callbacks': typeof DashboardCallbacksRoute
  '/dashboard/docs': typeof DashboardDocsRoute
  '/dashboard/keys': typeof DashboardKeysRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/bondpay-callback': typeof ApiPublicBondpayCallbackRoute
  '/api/public/proxy': typeof ApiPublicProxyRoute
  '/api/public/sametrend': typeof ApiPublicSametrendRoute
  '/api/public/wallet': typeof ApiPublicWalletRoute
  '/api/public/token/enter': typeof ApiPublicTokenEnterRoute
  '/api/public/token/issue': typeof ApiPublicTokenIssueRoute
  '/api/public/token/validate': typeof ApiPublicTokenValidateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/admin/cache'
    | '/admin/callbacks'
    | '/admin/clients'
    | '/admin/docs'
    | '/admin/health'
    | '/admin/integration'
    | '/admin/logs'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/transactions'
    | '/admin/users'
    | '/dashboard/callbacks'
    | '/dashboard/docs'
    | '/dashboard/keys'
    | '/dashboard/logs'
    | '/dashboard/transactions'
    | '/dashboard/wallet'
    | '/admin/'
    | '/dashboard/'
    | '/api/public/bondpay-callback'
    | '/api/public/proxy'
    | '/api/public/sametrend'
    | '/api/public/wallet'
    | '/api/public/token/enter'
    | '/api/public/token/issue'
    | '/api/public/token/validate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/admin/cache'
    | '/admin/callbacks'
    | '/admin/clients'
    | '/admin/docs'
    | '/admin/health'
    | '/admin/integration'
    | '/admin/logs'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/transactions'
    | '/admin/users'
    | '/dashboard/callbacks'
    | '/dashboard/docs'
    | '/dashboard/keys'
    | '/dashboard/logs'
    | '/dashboard/transactions'
    | '/dashboard/wallet'
    | '/admin'
    | '/dashboard'
    | '/api/public/bondpay-callback'
    | '/api/public/proxy'
    | '/api/public/sametrend'
    | '/api/public/wallet'
    | '/api/public/token/enter'
    | '/api/public/token/issue'
    | '/api/public/token/validate'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/admin/cache'
    | '/admin/callbacks'
    | '/admin/clients'
    | '/admin/docs'
    | '/admin/health'
    | '/admin/integration'
    | '/admin/logs'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/transactions'
    | '/admin/users'
    | '/dashboard/callbacks'
    | '/dashboard/docs'
    | '/dashboard/keys'
    | '/dashboard/logs'
    | '/dashboard/transactions'
    | '/dashboard/wallet'
    | '/admin/'
    | '/dashboard/'
    | '/api/public/bondpay-callback'
    | '/api/public/proxy'
    | '/api/public/sametrend'
    | '/api/public/wallet'
    | '/api/public/token/enter'
    | '/api/public/token/issue'
    | '/api/public/token/validate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiPublicBondpayCallbackRoute: typeof ApiPublicBondpayCallbackRoute
  ApiPublicProxyRoute: typeof ApiPublicProxyRoute
  ApiPublicSametrendRoute: typeof ApiPublicSametrendRoute
  ApiPublicWalletRoute: typeof ApiPublicWalletRoute
  ApiPublicTokenEnterRoute: typeof ApiPublicTokenEnterRoute
  ApiPublicTokenIssueRoute: typeof ApiPublicTokenIssueRoute
  ApiPublicTokenValidateRoute: typeof ApiPublicTokenValidateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/wallet': {
      id: '/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/transactions': {
      id: '/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/keys': {
      id: '/dashboard/keys'
      path: '/keys'
      fullPath: '/dashboard/keys'
      preLoaderRoute: typeof DashboardKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/docs': {
      id: '/dashboard/docs'
      path: '/docs'
      fullPath: '/dashboard/docs'
      preLoaderRoute: typeof DashboardDocsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/callbacks': {
      id: '/dashboard/callbacks'
      path: '/callbacks'
      fullPath: '/dashboard/callbacks'
      preLoaderRoute: typeof DashboardCallbacksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integration': {
      id: '/admin/integration'
      path: '/integration'
      fullPath: '/admin/integration'
      preLoaderRoute: typeof AdminIntegrationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/docs': {
      id: '/admin/docs'
      path: '/docs'
      fullPath: '/admin/docs'
      preLoaderRoute: typeof AdminDocsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/callbacks': {
      id: '/admin/callbacks'
      path: '/callbacks'
      fullPath: '/admin/callbacks'
      preLoaderRoute: typeof AdminCallbacksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cache': {
      id: '/admin/cache'
      path: '/cache'
      fullPath: '/admin/cache'
      preLoaderRoute: typeof AdminCacheRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/wallet': {
      id: '/api/public/wallet'
      path: '/api/public/wallet'
      fullPath: '/api/public/wallet'
      preLoaderRoute: typeof ApiPublicWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sametrend': {
      id: '/api/public/sametrend'
      path: '/api/public/sametrend'
      fullPath: '/api/public/sametrend'
      preLoaderRoute: typeof ApiPublicSametrendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proxy': {
      id: '/api/public/proxy'
      path: '/api/public/proxy'
      fullPath: '/api/public/proxy'
      preLoaderRoute: typeof ApiPublicProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bondpay-callback': {
      id: '/api/public/bondpay-callback'
      path: '/api/public/bondpay-callback'
      fullPath: '/api/public/bondpay-callback'
      preLoaderRoute: typeof ApiPublicBondpayCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/token/validate': {
      id: '/api/public/token/validate'
      path: '/api/public/token/validate'
      fullPath: '/api/public/token/validate'
      preLoaderRoute: typeof ApiPublicTokenValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/token/issue': {
      id: '/api/public/token/issue'
      path: '/api/public/token/issue'
      fullPath: '/api/public/token/issue'
      preLoaderRoute: typeof ApiPublicTokenIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/token/enter': {
      id: '/api/public/token/enter'
      path: '/api/public/token/enter'
      fullPath: '/api/public/token/enter'
      preLoaderRoute: typeof ApiPublicTokenEnterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCacheRoute: typeof AdminCacheRoute
  AdminCallbacksRoute: typeof AdminCallbacksRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminDocsRoute: typeof AdminDocsRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminIntegrationRoute: typeof AdminIntegrationRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStatsRoute: typeof AdminStatsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCacheRoute: AdminCacheRoute,
  AdminCallbacksRoute: AdminCallbacksRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminDocsRoute: AdminDocsRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminIntegrationRoute: AdminIntegrationRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStatsRoute: AdminStatsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardCallbacksRoute: typeof DashboardCallbacksRoute
  DashboardDocsRoute: typeof DashboardDocsRoute
  DashboardKeysRoute: typeof DashboardKeysRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardTransactionsRoute: typeof DashboardTransactionsRoute
  DashboardWalletRoute: typeof DashboardWalletRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCallbacksRoute: DashboardCallbacksRoute,
  DashboardDocsRoute: DashboardDocsRoute,
  DashboardKeysRoute: DashboardKeysRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardTransactionsRoute: DashboardTransactionsRoute,
  DashboardWalletRoute: DashboardWalletRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiPublicBondpayCallbackRoute: ApiPublicBondpayCallbackRoute,
  ApiPublicProxyRoute: ApiPublicProxyRoute,
  ApiPublicSametrendRoute: ApiPublicSametrendRoute,
  ApiPublicWalletRoute: ApiPublicWalletRoute,
  ApiPublicTokenEnterRoute: ApiPublicTokenEnterRoute,
  ApiPublicTokenIssueRoute: ApiPublicTokenIssueRoute,
  ApiPublicTokenValidateRoute: ApiPublicTokenValidateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
